CUDA_VISIBLE_DEVICES=0 python3 train_decoding.py --model_name LLMTranslator \
    --task_name task1_task2_task3 \
    --dataset_path ./data/ZuCo/ \
    --model_path ./models/bert-base-uncased \
    --llm_path ./models/llama-2-7b-hf \
    --save_path ./data/ZuCo/checkpoints/decoding \
    --one_step \
    --pretrained \
    --not_load_step1_checkpoint \
    --num_epoch_step1 20 \
    --num_epoch_step2 30 \
    --train_input EEG \
    -lr1 5e-4\
    -lr2 5e-4\
    -b 256 \
    -eeg GD \
